### ISSUE TITLE
Avalonia: Missing notification manager

### ISSUE THREAD

**Issue by milkywayfarer** [pr8x/DesktopNotifications#11]
Just added the code from Avalonia example to my project. Targeted the new SDK. Everything builds fine except the line: `public static INotificationManager notificationManager = AvaloniaLocator.Current.GetService<INotificationManager>()
            ?? throw new InvalidOperationException("Missing notification manager");` which throws.

**Comment by pr8x** [comment]
Do you call `SetupDesktopNotifications` during your app builder? https://github.com/pr8x/DesktopNotifications/blob/a7bccbe272010fd7a9ad995a8c1b04583a5acf2b/DesktopNotifications.Avalonia/AppBuilderExtensions.cs#L22

**Comment by milkywayfarer** [comment]
That did the job, thanks! For anyone wondering, add `.SetupDesktopNotifications()` to your `AppBuilder.Configure<App>()` in `Program.cs` file.
