### ISSUE TITLE
Progress of macOS support

### ISSUE THREAD

**Issue by laolarou726** [pr8x/DesktopNotifications#12]
Is there any progress for the macOS support? I'm trying to help with the MacOS API but I don't have any MacBook for now.

**Comment by pr8x** [comment]
Hey, I didn't have time to look into it yet. At least I convinced myself to buy a new M1 so I can actually start looking into soon.

**Comment by pr8x** [comment]
Closing this, since we already have https://github.com/pr8x/DesktopNotifications/issues/5 open
