### ISSUE TITLE
Build fails due to Microsoft.Toolkit.Uwp.Notifications package being a prelease

### ISSUE THREAD

**Issue by pr8x** [pr8x/DesktopNotifications#2]
Need to wait for stable release of Microsoft.Toolkit.Uwp.Notifications, which could take a while...

**Comment by pld32** [comment]
I tried the example with windows and worked great thanks. 
I a create a console app with .net code 3.1. Added your  projects as dependencies plus added them to the solution.
I have Microsoft.Toolkit.Uwp.Notifications packages added version 7.0.0.

I'm getting this error and not sure how to resolve. Can you suggest what to look at?

![Capture](https://user-images.githubusercontent.com/7564335/110973141-d9bf7380-832a-11eb-9a53-20516d3a7854.JPG)

**Comment by pld32** [comment]
Getting error in stable release  Microsoft.Toolkit.Uwp.Notifications 7.0.0. Any help would be great.

![Capture](https://user-images.githubusercontent.com/7564335/111156502-32ca1a00-856c-11eb-8c28-9ccabaf573d4.JPG)

**Comment by pr8x** [comment]
Updated to Microsoft.Toolkit.Uwp.Notifications 7.0.0 stable.
