### ISSUE TITLE
Version 1.3.0 fails with System.PlatformNotSupportedException on Windows

### ISSUE THREAD

**Issue by nefarius** [pr8x/DesktopNotifications#22]
Hey hey,

so I updated from 1.2.0 to 1.3.0 today and the same unchanged code now fails with 
```
System.PlatformNotSupportedException 
Operation is not supported on this platform.
   at DesktopNotifications.Windows.WindowsNotificationManager..ctor(WindowsApplicationContext context)
```

My code:

```cs
public partial class App : Application
{
    private readonly IHost _host;

    public App()
    {
        _host = Host.CreateDefaultBuilder()
            .ConfigureServices((hostContext, services) =>
            {
                services.AddSingleton<INotificationManager, WindowsNotificationManager>();

                services.AddHostedService<UpdateMessageSubscriber>();
            }).Build();
    }

    private async void App_OnStartup(object sender, StartupEventArgs e)
    {
        // throws exception now
        INotificationManager notificationManager = _host.Services.GetRequiredService<INotificationManager>();

        await notificationManager.Initialize();

        await _host.StartAsync();
    }
}
```

Thank you!

**Comment by pr8x** [comment]
Which platform are you running on?

**Comment by pr8x** [comment]
Oh I know why this is happening. I am creating nugets on the CI, but I only under ubuntu environment. So the windows package will be broken since it includes a nullimpl on non-windows platforms.

**Comment by nefarius** [comment]
> Which platform are you running on?

To answer your question, happens on both Windows 10 and 11.

**Comment by pr8x** [comment]
Now it seems to work on Windows (using 1.3.1) but fails to compile on Linux again (with `net6.0` target). Honestly multi-target and multi-OS stuff with .NET is pure horror.

**Comment by nefarius** [comment]
The error is gone now, thank you! Now I need to figure out why I am not getting any notifications whatsoever on Windows 11, but I haven't yet pinned down that issue to something with the library or not.

**Comment by pr8x** [comment]
Are you seeing the application in the windows Start menu?

**Comment by nefarius** [comment]
> Are you seeing the application in the windows Start menu?

Good point, I'll get back to you on this tomorrow.

**Comment by nefarius** [comment]
> Are you seeing the application in the windows Start menu?

Yep, it's there!

**Comment by nefarius** [comment]
Did a few more tests, nothing is appearing on Windows 11 22H2, no exceptions, nothing in Event Viewer... 🤔

**Comment by nefarius** [comment]
NVM just tried it in a fresh Windows 11 VM and there it works as expected, must be something wrong with the particular test machine, closing, thanks!
