### ISSUE TITLE
'Could not load ToastNotificationManagerCompat' error on Windows 10

### ISSUE THREAD

**Issue by AhNesh** [pr8x/DesktopNotifications#24]
When running on Windows 10 I get this error when creating a new WindowsNotificationManager:

```
DesktopNotifications.Windows.WindowsNotificationManager..ctor(DesktopNotifications.Windows.WindowsApplicationContext ): System.TypeLoadException: Could not load type 'Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat' from assembly 'Microsoft.Toolkit.Uwp.Notifications, Version=7.1.0.0, Culture=neutral, PublicKeyToken=4aff67a105548ee2'.
```

I can find this in the project dependencies

![image](https://github.com/pr8x/DesktopNotifications/assets/33862238/b048d9a9-ee89-49d7-93f0-96243d1c3089)

**Comment by kqr** [comment]
Quoting @pr8x in another issue:

> Make sure to target either net6.0-windows10.0.17763.0 or n etcoreapp3.1 in your application. It doesn't wotk with net6.0 unfortunately due to the windows-specific TFM used internally. I will add a note about that in the readme.

This solved that same problem for me.

**Comment by AhNesh** [comment]
Changing to target net6.0-windows10.0.17763.0 fixed it. Thanks.
