### ISSUE TITLE
Question - .net5

### ISSUE THREAD

**Issue by pld32** [pr8x/DesktopNotifications#4]
Is this .net5 ready or will it be?

And I'm new is this how you ask questions?

**Comment by maxkatz6** [comment]
Yes, it's a correct place for questions.

Have you tried to use it? .NET Core 3.1 is compatible with .NET 5.

**Comment by pld32** [comment]
I just tried and getting some errors in DesktopNotifications.Windows WindowsNotificationManager.cs. 

Attached is the error list.

[DeskTopNotificationsErrors.txt](https://github.com/pr8x/DesktopNotifications/files/6850402/DeskTopNotificationsErrors.txt)

**Comment by pr8x** [comment]
Which version of Windows are you on? Can you create a repro?

**Comment by maxkatz6** [comment]
I see. Windows package uses Microsoft.Toolkit.Uwp.Notifications, which uses legacy WinRT COM Interop, which was removed from .NET 5. Not sure if Microsoft.Toolkit.Uwp.Notifications was updated to work with newer CsWinRT COM Interop, but if it does - multitarget for "net5.0;netcoreapp3.1" in this package should work. @pr8x

**Comment by pr8x** [comment]
It seems that with .NET 5 I cannot reference `Microsoft.Toolkit.Uwp.Notifications` anymore but instead have to use their "Target Framework Moniker" (https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance#net-5-use-the-target-framework-moniker-option) 

Tried `net5.0-windows10.0.17763.0` but that doesn't support some stuff like `ToastContentBuilder` or `ToastNotificationManagerCompat`.

**Comment by maxkatz6** [comment]
Related https://blogs.windows.com/windowsdeveloper/2021/03/16/announcing-windows-community-toolkit-v7-0/

> Tried net5.0-windows10.0.17763.0 but that doesn't support some stuff like ToastContentBuilder or ToastNotificationManagerCompat

Yes, something might be missed
